add rustfmt action, disable exit on error on clippy

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -119,6 +119,53 @@ jobs:
         run: npm run testenv:stop
         if: always()
 
+  rustfmt:
+    name: rustfmt
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+
+      - name: Rustfmt Job Summary
+        run: |
+          # Run cargo and store the original output
+          CARGO_STATUS=0
+          CARGO_OUTPUT=$(cargo fmt --all --manifest-path=Cargo.toml -- --config group_imports=StdExternalCrate,imports_granularity=Module --color=always --check 2>/dev/null) || CARGO_STATUS=$?
+
+          if [ ${CARGO_STATUS} -eq 0 ]; then
+              cat <<MARKDOWN_INTRO >> $GITHUB_STEP_SUMMARY
+          # Rustfmt Results
+
+          The code is formatted perfectly!
+          MARKDOWN_INTRO
+          else
+              cat <<MARKDOWN_INTRO >> $GITHUB_STEP_SUMMARY
+          # Rustfmt Results
+
+          \`cargo fmt\` reported formatting errors in the following locations.
+          You can fix them by executing the following command and committing the changes.
+          \`\`\`bash
+          cargo fmt --all
+          \`\`\`
+          MARKDOWN_INTRO
+
+              echo "${CARGO_OUTPUT}" |
+                  # Strip color codes
+                  sed 's/\x1B\[[0-9;]*[A-Za-z]\x0f\?//g' |
+                  # Strip (some) cursor movements
+                  sed 's/\x1B.[A-G]//g' |
+                  tr "\n" "\r" |
+                  # Wrap each location into a HTML details
+                  sed -E 's#Diff in ([^\r]*?)( at line |:)([[:digit:]]+):\r((:?[ +-][^\r]*\r)+)#<details>\n<summary>\1:\3</summary>\n\n```diff\n\4```\n\n</details>\n\n#g' |
+                  tr "\r" "\n" >> $GITHUB_STEP_SUMMARY
+          fi
+
+          # Print the original cargo message
+          echo "${CARGO_OUTPUT}"
+          # Exit with the same status as cargo
+          exit "${CARGO_STATUS}"
+
   clippy:
     name: rust-clippy
     runs-on: ubuntu-latest
@@ -126,13 +173,13 @@ jobs:
       - uses: actions/checkout@v4
         with:
           persist-credentials: false
-      - name: Update Rust
-        run: |
-          rustup update
-          cargo install --force cargo-tarpaulin
+
       - name: Run clippy
         id: clippy
         run: |
+          # Disable immediate exit on error
+          set +e
+
           # Run clippy and capture output
           CLIPPY_OUTPUT=$(cargo bitcoin-indexer-clippy-cli 2>&1)
           CLIPPY_EXIT_CODE=$?
@@ -146,6 +193,10 @@ jobs:
           else
             echo "status=success" >> $GITHUB_OUTPUT
           fi
+
+          # Enable immediate exit on error again
+          set -e
+
       - name: Create error summary
         if: steps.clippy.outputs.status == 'failed'
         run: |
