ci clippy simplified

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -215,35 +215,39 @@ jobs:
         with:
           toolchain: '1.85'
           components: clippy
-
-      - name: Run clippy
+       
+       - name: Run clippy
         id: clippy
-        run: |
-          # Disable immediate exit on error
-          set +e
+        run: cargo bitcoin-indexer-clippy
 
-          # Run clippy and capture output
-          LIBCLANG_PATH=/usr/lib/llvm-18/lib RUST_BACKTRACE=full cargo bitcoin-indexer-clippy-cli 2>&1 | tee /tmp/clippy_output.log
-          CLIPPY_EXIT_CODE=${PIPESTATUS[0]}
+      # - name: Run clippy
+      #   id: clippy
+      #   run: |
+      #     # Disable immediate exit on error
+      #     set +e
 
-          # Print output if clippy failed
-          if [ $CLIPPY_EXIT_CODE -ne 0 ]; then
-            echo "## ❌ Clippy Check Failed
+      #     # Run clippy and capture output
+      #     RUST_BACKTRACE=full cargo bitcoin-indexer-clippy-cli 2>&1 | tee /tmp/clippy_output.log
+      #     CLIPPY_EXIT_CODE=${PIPESTATUS[0]}
 
-          To see and fix these issues, run:
-          \`\`\`bash
-          cargo bitcoin-indexer-clippy
-          \`\`\`
+      #     # Print output if clippy failed
+      #     if [ $CLIPPY_EXIT_CODE -ne 0 ]; then
+      #       echo "## ❌ Clippy Check Failed
 
-          ### Clippy Errors
-          \`\`\`
-          $(cat /tmp/clippy_output.log | grep -E '(error\:)|(warning\:)')
-          \`\`\`" >> $GITHUB_STEP_SUMMARY
-          fi
+      #     To see and fix these issues, run:
+      #     \`\`\`bash
+      #     cargo bitcoin-indexer-clippy
+      #     \`\`\`
 
-          # Enable immediate exit on error again
-          set -e
-          exit $CLIPPY_EXIT_CODE
+      #     ### Clippy Errors
+      #     \`\`\`
+      #     $(cat /tmp/clippy_output.log | grep -E '(error\:)|(warning\:)')
+      #     \`\`\`" >> $GITHUB_STEP_SUMMARY
+      #     fi
+
+      #     # Enable immediate exit on error again
+      #     set -e
+      #     exit $CLIPPY_EXIT_CODE
 
   test:
     strategy:
